// Generated by LiveScript 1.5.0
"use strict";
var agent, host, winName, form, $id, $q, every, timeIt, getLastSegment, getStep, getCargo, getHTML, collectData, sendData, timer;
agent = "GVReporter/1.0.0";
host = "https://gv.erinome.net/reporter";
winName = 'gv-reporter-win';
form = null;
$id = function(it){
  return document.getElementById(it);
};
$q = function(it){
  return document.querySelector(it);
};
every = function(ms, action){
  return setInterval(action, ms);
};
timeIt = function(title, action){
  console.time(title);
  try {
    return action();
  } finally {
    console.timeEnd(title);
  }
};
getLastSegment = function(url){
  return /\/([^\/]*?)(?:\#.*)?$/.exec(url)[1];
};
getStep = function(){
  var e;
  try {
    return +/\d+/.exec($q('#m_fight_log .block_h .block_title').textContent)[0];
  } catch (e$) {
    e = e$;
    return 0;
  }
};
getCargo = function(){
  var e;
  try {
    return $q('#hk_cargo .l_val').textContent;
  } catch (e$) {
    e = e$;
    return "";
  }
};
getHTML = function(id){
  var e;
  try {
    return $id(id).outerHTML;
  } catch (e$) {
    e = e$;
    return "";
  }
};
collectData = function(){
  return timeIt("Collected", function(){
    return {
      step: getStep(),
      cargo: getCargo(),
      data: base64js.fromByteArray(pako.deflate(['alls', 's_map', 'm_fight_log'].map(getHTML).join("<&>")))
    };
  });
};
sendData = function(data){
  var i$, x$, ref$, len$, that;
  for (i$ = 0, len$ = (ref$ = form.children).length; i$ < len$; ++i$) {
    x$ = ref$[i$];
    if ((that = data[x$.name]) != null) {
      x$.value = that;
    }
  }
  open("about:blank", winName, "toolbar=no,scrollbars=no,location=no,status=no,menubar=no,resizable=no,height=150,width=243");
  document.body.appendChild(form);
  form.submit();
  document.body.removeChild(form);
};
timer = every(300, function(){
  var localLink, heroBlock, streamingLink;
  if (!($id('hero_columns') != null && window.pako != null && window.base64js != null)) {
    return;
  }
  clearInterval(timer);
  if ($id('s_map') == null) {
    return;
  }
  form = document.createElement('form');
  form.method = 'POST';
  form.action = host + "/send";
  form.enctype = "multipart/form-data";
  form.acceptCharset = 'utf-8';
  form.target = winName;
  form.style.display = 'none';
  localLink = "" + location.protocol + "//" + location.host + "" + $id('fbclink').href.replace(/^(?:\w*:\/\/)?[^\/]*/, "") + "";
  form.innerHTML = "<input type='hidden' name='protocolVersion' value='1' /><input type='hidden' name='agent' value='" + agent + "' /><input type='hidden' name='link' value='" + localLink + "' /><input type='hidden' name='stepDuration' value='20' /><input type='hidden' name='scale' value='11' /><input type='hidden' name='step' /><input type='hidden' name='playerIndex' value='0' /><input type='hidden' name='cargo' /><input type='hidden' name='data' />";
  heroBlock = $id('hero_block');
  heroBlock.insertAdjacentHTML('afterbegin', "<div style='text-align: center;'><a href='#' target='_blank'>Транслировать</a></div>");
  streamingLink = heroBlock.firstChild.firstChild;
  streamingLink.onclick = function(){
    var data, lastStep;
    streamingLink.textContent = "Идёт трансляция";
    streamingLink.href = host + "/duels/log/" + getLastSegment(localLink);
    streamingLink.onclick = null;
    data = collectData();
    lastStep = data.step;
    sendData(data);
    every(500, function(){
      var step;
      if ((step = getStep()) > lastStep) {
        lastStep = step;
        sendData(collectData());
      }
    });
    return false;
  };
});